# Churn Prediction Project Configuration

# Data Processing Parameters
data_processing:
  observation_days: 5          # Days for observation period
  churn_period_days: 10        # Days for churn prediction period
  train_ratio: 0.8             # Train/eval split ratio
  random_seed: 42              # Random seed for reproducibility

# Directory Paths (relative to project root)
paths:
  data_dir: "src/data"
  processed_dir: "src/data/processed"
  logs_dir: "logs"
  results_dir: "results"

# Logging Configuration
logging:
  level: "INFO"                # DEBUG, INFO, WARNING, ERROR, CRITICAL
  console: true                # Log to console
  file: true                   # Log to file

# Performance Settings
performance:
  batch_size: 1000             # Batch size for processing
  progress_interval: 1000      # Progress logging interval 